DELETE FROM `trinity_string` WHERE `entry` IN (11100, 11101, 11102, 11103, 11104, 11105, 11106, 11107, 11108, 11109, 11110, 11130, 11131, 11132, 11133, 11134, 11135, 11136, 11137, 11138, 11139, 11140, 11141, 11142, 11143, 11144, 11145, 11146, 11147, 11148, 11149, 11150, 11151, 11152, 11153, 11154, 11155, 11156, 11157, 11158, 11159, 11160, 11161, 11162);
INSERT INTO `trinity_string` VALUES (11100, '装备已幻化', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11101, 'Equipment slot is empty', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11102, 'Invalid source item selected', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11103, 'Source item does not exist', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11104, 'Destination item does not exist', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11105, 'Selected items are invalid', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11106, '你的钱不够', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11107, 'You don\'t have enough tokens', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11108, '幻化移除', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11109, '没有幻化', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11110, 'Invalid name inserted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11130, '头部', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11131, '肩膀', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11132, '衬衣', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11133, '胸部', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11134, '腰部', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11135, '腿部', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11136, '脚', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11137, '腕部', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11138, '手', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11139, '背部', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11140, '主手', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11141, '副手', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11142, '远程武器', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11143, '战袍', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11144, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|t 请选择一个项目', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11145, '|TInterface/RAIDFRAME/UI-RAIDFRAME-MAINASSIST:30:30:-18:0|t管理幻化', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11146, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|t移除所有幻化', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11147, '移除所有幻化？', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11148, '|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|t刷新菜单', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11149, '|TInterface/ICONS/INV_Misc_Book_11:30:30:-18:0|t请选择一个', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11150, '|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|t保存', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11151, '|TInterface/ICONS/Ability_Spy:30:30:-18:0|t返回', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11152, '|TInterface/ICONS/INV_Misc_Statue_02:30:30:-18:0|tUse set', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11153, 'Using this set for transmogrify will bind transmogrified items to you and make them non-refundable and non-tradeable.\\nDo you wish to continue?\\n\\n', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11154, '|TInterface/PaperDollInfoFrame/UI-GearManager-LeaveItem-Opaque:30:30:-18:0|tDelete set', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11155, 'Are you sure you want to delete', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11156, '|TInterface/GuildBankFrame/UI-GuildBankFrame-NewTab:30:30:-18:0|t保存', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11157, 'Insert set name', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11158, '|TInterface/PaperDollInfoFrame/UI-GearManager-Undo:30:30:-18:0|t刷新菜单', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11159, '如果执行幻化操作，此项装备将无法交易，无法退还. 确定幻化?                                      ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11160, '如果执行幻化操作，此项装备将无法交易，无法退还. 确定幻化?                                      ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11161, '|TInterface/ICONS/INV_Enchant_Disenchant:30:30:-18:0|t移除所有幻化', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `trinity_string` VALUES (11162, '移除此项幻化？', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
