INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9000', 'npcbot add');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9001', 'npcbot info');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9002', 'npcbot fuhuo');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9003', 'npcbot shan');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9004', 'npcbot shuaxin');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9005', 'npcbot command');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9006', 'npcbot juli');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9007', 'npcbot helper');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9008', 'mt');
INSERT INTO `rbac_permissions` (`id`, `name`) VALUES ('9009', 'npcbot');

INSERT INTO `rbac_role_permissions` VALUES (1, 9000);
INSERT INTO `rbac_role_permissions` VALUES (1, 9001);
INSERT INTO `rbac_role_permissions` VALUES (1, 9002);
INSERT INTO `rbac_role_permissions` VALUES (1, 9003);
INSERT INTO `rbac_role_permissions` VALUES (1, 9004);
INSERT INTO `rbac_role_permissions` VALUES (1, 9005);
INSERT INTO `rbac_role_permissions` VALUES (1, 9006);
INSERT INTO `rbac_role_permissions` VALUES (1, 9007);
INSERT INTO `rbac_role_permissions` VALUES (1, 9008);
INSERT INTO `rbac_role_permissions` VALUES (1, 9009);