UPDATE `areatrigger_tavern` SET `id` = 71,`name` = '西部荒野 - 哨兵岭旅店' WHERE `areatrigger_tavern`.`id` = 71;
UPDATE `areatrigger_tavern` SET `id` = 562,`name` = '艾尔文森林 - 闪金镇 - 狮王之傲旅店' WHERE `areatrigger_tavern`.`id` = 562;
UPDATE `areatrigger_tavern` SET `id` = 682,`name` = '赤脊山 - 湖畔旅店' WHERE `areatrigger_tavern`.`id` = 682;
UPDATE `areatrigger_tavern` SET `id` = 707,`name` = '暮色森林 - 夜色 - 血色旅店' WHERE `areatrigger_tavern`.`id` = 707;
UPDATE `areatrigger_tavern` SET `id` = 708,`name` = '希尔斯布莱德丘陵 - 南海镇的旅店' WHERE `areatrigger_tavern`.`id` = 708;
UPDATE `areatrigger_tavern` SET `id` = 709,`name` = '尘泥沼泽 - 塞拉摩岛' WHERE `areatrigger_tavern`.`id` = 709;
UPDATE `areatrigger_tavern` SET `id` = 710,`name` = '丹莫罗 - 卡拉诺斯 - 雷酒厂' WHERE `areatrigger_tavern`.`id` = 710;
UPDATE `areatrigger_tavern` SET `id` = 712,`name` = '洛克莫丹 - 在塞尔萨玛 - 烈酒旅店' WHERE `areatrigger_tavern`.`id` = 712;
UPDATE `areatrigger_tavern` SET `id` = 713,`name` = '湿地 - 米奈希尔港 - 深水酒馆' WHERE `areatrigger_tavern`.`id` = 713;
UPDATE `areatrigger_tavern` SET `id` = 715,`name` = '泰达希尔 - 多兰纳尔' WHERE `areatrigger_tavern`.`id` = 715;
UPDATE `areatrigger_tavern` SET `id` = 716,`name` = '黑海岸 - 奥伯丁' WHERE `areatrigger_tavern`.`id` = 716;
UPDATE `areatrigger_tavern` SET `id` = 717,`name` = '梣谷 - 阿斯特兰纳' WHERE `areatrigger_tavern`.`id` = 717;
UPDATE `areatrigger_tavern` SET `id` = 719,`name` = '提里斯法林地 - 布瑞尔 - 恐惧之末旅店' WHERE `areatrigger_tavern`.`id` = 719;
UPDATE `areatrigger_tavern` SET `id` = 720,`name` = '银松森林' WHERE `areatrigger_tavern`.`id` = 720;
UPDATE `areatrigger_tavern` SET `id` = 721,`name` = '希尔斯布莱德丘陵' WHERE `areatrigger_tavern`.`id` = 721;
UPDATE `areatrigger_tavern` SET `id` = 722,`name` = '莫高雷' WHERE `areatrigger_tavern`.`id` = 722;
UPDATE `areatrigger_tavern` SET `id` = 742,`name` = '贫瘠之地' WHERE `areatrigger_tavern`.`id` = 742;
UPDATE `areatrigger_tavern` SET `id` = 743,`name` = '贫瘠之地' WHERE `areatrigger_tavern`.`id` = 743;
UPDATE `areatrigger_tavern` SET `id` = 843,`name` = '杜洛塔' WHERE `areatrigger_tavern`.`id` = 843;
UPDATE `areatrigger_tavern` SET `id` = 844,`name` = '悲伤沼泽' WHERE `areatrigger_tavern`.`id` = 844;
UPDATE `areatrigger_tavern` SET `id` = 862,`name` = '荆棘谷' WHERE `areatrigger_tavern`.`id` = 862;
UPDATE `areatrigger_tavern` SET `id` = 982,`name` = '贫瘠之地' WHERE `areatrigger_tavern`.`id` = 982;
UPDATE `areatrigger_tavern` SET `id` = 4241,`name` = '血谜岛 - 血色守望旅店' WHERE `areatrigger_tavern`.`id` = 4241;
UPDATE `areatrigger_tavern` SET `id` = 1022,`name` = '石爪山脉' WHERE `areatrigger_tavern`.`id` = 1022;
UPDATE `areatrigger_tavern` SET `id` = 1023,`name` = '塔纳利斯' WHERE `areatrigger_tavern`.`id` = 1023;
UPDATE `areatrigger_tavern` SET `id` = 1024,`name` = '菲拉斯' WHERE `areatrigger_tavern`.`id` = 1024;
UPDATE `areatrigger_tavern` SET `id` = 1025,`name` = '菲拉斯' WHERE `areatrigger_tavern`.`id` = 1025;
UPDATE `areatrigger_tavern` SET `id` = 1606,`name` = '废地' WHERE `areatrigger_tavern`.`id` = 1606;
UPDATE `areatrigger_tavern` SET `id` = 1646,`name` = '阿拉希高地' WHERE `areatrigger_tavern`.`id` = 1646;
UPDATE `areatrigger_tavern` SET `id` = 2266,`name` = '凄凉之地' WHERE `areatrigger_tavern`.`id` = 2266;
UPDATE `areatrigger_tavern` SET `id` = 2267,`name` = '凄凉之地' WHERE `areatrigger_tavern`.`id` = 2267;
UPDATE `areatrigger_tavern` SET `id` = 2286,`name` = '千针石林' WHERE `areatrigger_tavern`.`id` = 2286;
UPDATE `areatrigger_tavern` SET `id` = 2287,`name` = '冬泉谷' WHERE `areatrigger_tavern`.`id` = 2287;
UPDATE `areatrigger_tavern` SET `id` = 2610,`name` = '梣谷' WHERE `areatrigger_tavern`.`id` = 2610;
UPDATE `areatrigger_tavern` SET `id` = 2786,`name` = '暴风城休息站' WHERE `areatrigger_tavern`.`id` = 2786;
UPDATE `areatrigger_tavern` SET `id` = 4108,`name` = '安宁旅店' WHERE `areatrigger_tavern`.`id` = 4108;
UPDATE `areatrigger_tavern` SET `id` = 4240,`name` = '碧蓝岗哨旅店' WHERE `areatrigger_tavern`.`id` = 4240;
UPDATE `areatrigger_tavern` SET `id` = 4336,`name` = '萨尔玛旅店' WHERE `areatrigger_tavern`.`id` = 4336;
UPDATE `areatrigger_tavern` SET `id` = 4337,`name` = '荣耀堡旅店' WHERE `areatrigger_tavern`.`id` = 4337;
UPDATE `areatrigger_tavern` SET `id` = 4373,`name` = '萨布拉金旅店' WHERE `areatrigger_tavern`.`id` = 4373;
UPDATE `areatrigger_tavern` SET `id` = 4375,`name` = '如卡拉达尔快捷酒店' WHERE `areatrigger_tavern`.`id` = 4375;
UPDATE `areatrigger_tavern` SET `id` = 4376,`name` = '泰拉旅店' WHERE `areatrigger_tavern`.`id` = 4376;
UPDATE `areatrigger_tavern` SET `id` = 4377,`name` = '艾兰理堡垒旅店' WHERE `areatrigger_tavern`.`id` = 4377;
UPDATE `areatrigger_tavern` SET `id` = 4382,`name` = '塞纳里奥避难所' WHERE `areatrigger_tavern`.`id` = 4382;
UPDATE `areatrigger_tavern` SET `id` = 4486,`name` = '猎鹰之翼广场旅店' WHERE `areatrigger_tavern`.`id` = 4486;
UPDATE `areatrigger_tavern` SET `id` = 4526,`name` = '影月村旅店' WHERE `areatrigger_tavern`.`id` = 4526;
UPDATE `areatrigger_tavern` SET `id` = 4528,`name` = '蛮锤要塞旅店' WHERE `areatrigger_tavern`.`id` = 4528;
UPDATE `areatrigger_tavern` SET `id` = 4595,`name` = '摩克纳萨尔村旅店' WHERE `areatrigger_tavern`.`id` = 4595;
UPDATE `areatrigger_tavern` SET `id` = 4607,`name` = '星光圣所旅店' WHERE `areatrigger_tavern`.`id` = 4607;
UPDATE `areatrigger_tavern` SET `id` = 4374,`name` = '泰伦多尔旅店' WHERE `areatrigger_tavern`.`id` = 4374;
UPDATE `areatrigger_tavern` SET `id` = 4383,`name` = '奥雷伯尔港旅店' WHERE `areatrigger_tavern`.`id` = 4383;
UPDATE `areatrigger_tavern` SET `id` = 4381,`name` = '特尔哈曼神庙旅店' WHERE `areatrigger_tavern`.`id` = 4381;
UPDATE `areatrigger_tavern` SET `id` = 4499,`name` = '希尔瓦纳旅店' WHERE `areatrigger_tavern`.`id` = 4499;
UPDATE `areatrigger_tavern` SET `id` = 4558,`name` = '托斯利基地旅店' WHERE `areatrigger_tavern`.`id` = 4558;
UPDATE `areatrigger_tavern` SET `id` = 4494,`name` = '雷霆王村旅店' WHERE `areatrigger_tavern`.`id` = 4494;
UPDATE `areatrigger_tavern` SET `id` = 4640,`name` = '永恒树林旅店' WHERE `areatrigger_tavern`.`id` = 4640;
UPDATE `areatrigger_tavern` SET `id` = 4521,`name` = '52区旅店' WHERE `areatrigger_tavern`.`id` = 4521;
UPDATE `areatrigger_tavern` SET `id` = 4555,`name` = '风暴之尖旅店' WHERE `areatrigger_tavern`.`id` = 4555;
UPDATE `areatrigger_tavern` SET `id` = 4577,`name` = '萨塔祭坛' WHERE `areatrigger_tavern`.`id` = 4577;
UPDATE `areatrigger_tavern` SET `id` = 178,`name` = '斯坦恩布莱德' WHERE `areatrigger_tavern`.`id` = 178;
UPDATE `areatrigger_tavern` SET `id` = 1042,`name` = '蛮锤城堡' WHERE `areatrigger_tavern`.`id` = 1042;
UPDATE `areatrigger_tavern` SET `id` = 3690,`name` = '恶齿村' WHERE `areatrigger_tavern`.`id` = 3690;
UPDATE `areatrigger_tavern` SET `id` = 3886,`name` = '格罗姆高营地' WHERE `areatrigger_tavern`.`id` = 3886;
UPDATE `areatrigger_tavern` SET `id` = 4058,`name` = '圣光之愿礼拜堂' WHERE `areatrigger_tavern`.`id` = 4058;
UPDATE `areatrigger_tavern` SET `id` = 3985,`name` = '塞纳里奥城堡' WHERE `areatrigger_tavern`.`id` = 3985;
UPDATE `areatrigger_tavern` SET `id` = 4090,`name` = '石爪峰' WHERE `areatrigger_tavern`.`id` = 4090;
UPDATE `areatrigger_tavern` SET `id` = 3547,`name` = '幽暗城' WHERE `areatrigger_tavern`.`id` = 3547;
UPDATE `areatrigger_tavern` SET `id` = 4769,`name` = '铁炉堡大门' WHERE `areatrigger_tavern`.`id` = 4769;
UPDATE `areatrigger_tavern` SET `id` = 4714,`name` = '泥链营地旅店' WHERE `areatrigger_tavern`.`id` = 4714;
UPDATE `areatrigger_tavern` SET `id` = 4775,`name` = '蕨墙村旅店' WHERE `areatrigger_tavern`.`id` = 4775;
UPDATE `areatrigger_tavern` SET `id` = 4847,`name` = '奎尔丹纳斯岛，日境港酒店' WHERE `areatrigger_tavern`.`id` = 4847;
UPDATE `areatrigger_tavern` SET `id` = 4961,`name` = '骁勇要塞旅店' WHERE `areatrigger_tavern`.`id` = 4961;
UPDATE `areatrigger_tavern` SET `id` = 4867,`name` = '嘶轴简易机场旅店' WHERE `areatrigger_tavern`.`id` = 4867;
UPDATE `areatrigger_tavern` SET `id` = 4977,`name` = '昂纽沛旅店' WHERE `areatrigger_tavern`.`id` = 4977;
UPDATE `areatrigger_tavern` SET `id` = 4868,`name` = '坦卡雷村旅店' WHERE `areatrigger_tavern`.`id` = 4868;
UPDATE `areatrigger_tavern` SET `id` = 4910,`name` = '战歌堡' WHERE `areatrigger_tavern`.`id` = 4910;
UPDATE `areatrigger_tavern` SET `id` = 4861,`name` = '博格洛克前哨旅店' WHERE `areatrigger_tavern`.`id` = 4861;
UPDATE `areatrigger_tavern` SET `id` = 4755,`name` = '冬蹄营地旅店' WHERE `areatrigger_tavern`.`id` = 4755;
UPDATE `areatrigger_tavern` SET `id` = 4756,`name` = '威德瓦堡垒旅店' WHERE `areatrigger_tavern`.`id` = 4756;
UPDATE `areatrigger_tavern` SET `id` = 5045,`name` = '阿格玛之锤' WHERE `areatrigger_tavern`.`id` = 5045;
UPDATE `areatrigger_tavern` SET `id` = 4964,`name` = '繁星之眠' WHERE `areatrigger_tavern`.`id` = 4964;
UPDATE `areatrigger_tavern` SET `id` = 4965,`name` = '琥珀松小屋旅店' WHERE `areatrigger_tavern`.`id` = 4965;
UPDATE `areatrigger_tavern` SET `id` = 4966,`name` = '西荒兵团驻营' WHERE `areatrigger_tavern`.`id` = 4966;
UPDATE `areatrigger_tavern` SET `id` = 4967,`name` = '欧尼克瓦营地' WHERE `areatrigger_tavern`.`id` = 4967;
UPDATE `areatrigger_tavern` SET `id` = 4970,`name` = '征服堡' WHERE `areatrigger_tavern`.`id` = 4970;
UPDATE `areatrigger_tavern` SET `id` = 4975,`name` = '默亚基港' WHERE `areatrigger_tavern`.`id` = 4975;
UPDATE `areatrigger_tavern` SET `id` = 4976,`name` = '卡玛廓' WHERE `areatrigger_tavern`.`id` = 4976;
UPDATE `areatrigger_tavern` SET `id` = 4979,`name` = '毒怨之地' WHERE `areatrigger_tavern`.`id` = 4979;
UPDATE `areatrigger_tavern` SET `id` = 4993,`name` = '温特加德要塞' WHERE `areatrigger_tavern`.`id` = 4993;
UPDATE `areatrigger_tavern` SET `id` = 5030,`name` = '矛生驻营' WHERE `areatrigger_tavern`.`id` = 5030;
UPDATE `areatrigger_tavern` SET `id` = 5062,`name` = '银白看台' WHERE `areatrigger_tavern`.`id` = 5062;
UPDATE `areatrigger_tavern` SET `id` = 5164,`name` = '辛讬加' WHERE `areatrigger_tavern`.`id` = 5164;
UPDATE `areatrigger_tavern` SET `id` = 5182,`name` = '霜堡' WHERE `areatrigger_tavern`.`id` = 5182;
UPDATE `areatrigger_tavern` SET `id` = 5183,`name` = 'K3' WHERE `areatrigger_tavern`.`id` = 5183;
UPDATE `areatrigger_tavern` SET `id` = 5200,`name` = '布伦希尔达村' WHERE `areatrigger_tavern`.`id` = 5200;
UPDATE `areatrigger_tavern` SET `id` = 5204,`name` = '石崖避难所' WHERE `areatrigger_tavern`.`id` = 5204;
UPDATE `areatrigger_tavern` SET `id` = 5217,`name` = '奈辛瓦里营地' WHERE `areatrigger_tavern`.`id` = 5217;
UPDATE `areatrigger_tavern` SET `id` = 5227,`name` = '银白先锋' WHERE `areatrigger_tavern`.`id` = 5227;
UPDATE `areatrigger_tavern` SET `id` = 5323,`name` = '坦卡罗营地' WHERE `areatrigger_tavern`.`id` = 5323;
UPDATE `areatrigger_tavern` SET `id` = 5327,`name` = '卡萨斯平台' WHERE `areatrigger_tavern`.`id` = 5327;
UPDATE `areatrigger_tavern` SET `id` = 4753,`name` = '镇西旅店' WHERE `areatrigger_tavern`.`id` = 4753;
UPDATE `areatrigger_tavern` SET `id` = 4265,`name` = '晴风村旅店' WHERE `areatrigger_tavern`.`id` = 4265;
UPDATE `areatrigger_tavern` SET `id` = 98,`name` = '奈辛瓦里远征队营地' WHERE `areatrigger_tavern`.`id` = 98;
UPDATE `areatrigger_tavern` SET `id` = 4109,`name` = '安宁地旅店（上层）' WHERE `areatrigger_tavern`.`id` = 4109;
UPDATE `areatrigger_tavern` SET `id` = 4300,`name` = '塞纳里奥难民 - 外旅店' WHERE `areatrigger_tavern`.`id` = 4300;
UPDATE `areatrigger_tavern` SET `id` = 4378,`name` = '石堡旅店' WHERE `areatrigger_tavern`.`id` = 4378;
UPDATE `areatrigger_tavern` SET `id` = 4380,`name` = '猎鹰岗哨旅店' WHERE `areatrigger_tavern`.`id` = 4380;
UPDATE `areatrigger_tavern` SET `id` = 4498,`name` = '旧希尔斯布莱德丘陵旅店' WHERE `areatrigger_tavern`.`id` = 4498;
UPDATE `areatrigger_tavern` SET `id` = 4608,`name` = '圣殿的星星旅店（上层）' WHERE `areatrigger_tavern`.`id` = 4608;
UPDATE `areatrigger_tavern` SET `id` = 5314,`name` = '龙眠神殿' WHERE `areatrigger_tavern`.`id` = 5314;
UPDATE `areatrigger_tavern` SET `id` = 5315,`name` = '龙眠神殿' WHERE `areatrigger_tavern`.`id` = 5315;
UPDATE `areatrigger_tavern` SET `id` = 5316,`name` = '龙眠神殿' WHERE `areatrigger_tavern`.`id` = 5316;
UPDATE `areatrigger_tavern` SET `id` = 5317,`name` = '龙眠神殿...' WHERE `areatrigger_tavern`.`id` = 5317;