UPDATE `areatrigger_teleport` SET `id` = 45,`name` = '血色修道院西(墓地)副本起点' WHERE `areatrigger_teleport`.`id` = 45;
UPDATE `areatrigger_teleport` SET `id` = 78,`name` = '死亡矿井(副本)A-西部荒野' WHERE `areatrigger_teleport`.`id` = 78;
UPDATE `areatrigger_teleport` SET `id` = 101,`name` = '暴风城监狱-(副本)入口' WHERE `areatrigger_teleport`.`id` = 101;
UPDATE `areatrigger_teleport` SET `id` = 107,`name` = '暴风城地窑' WHERE `areatrigger_teleport`.`id` = 107;
UPDATE `areatrigger_teleport` SET `id` = 109,`name` = '暴风城地窑' WHERE `areatrigger_teleport`.`id` = 109;
UPDATE `areatrigger_teleport` SET `id` = 119,`name` = '死亡矿井A门口-西部荒野' WHERE `areatrigger_teleport`.`id` = 119;
UPDATE `areatrigger_teleport` SET `id` = 121,`name` = '死亡矿井B出口-西部荒野' WHERE `areatrigger_teleport`.`id` = 121;
UPDATE `areatrigger_teleport` SET `id` = 145,`name` = '影牙城堡(副本)-银松森林' WHERE `areatrigger_teleport`.`id` = 145;
UPDATE `areatrigger_teleport` SET `id` = 194,`name` = '影牙城堡 -入口' WHERE `areatrigger_teleport`.`id` = 194;
UPDATE `areatrigger_teleport` SET `id` = 226,`name` = '哀嚎洞穴门口-贫瘠之地' WHERE `areatrigger_teleport`.`id` = 226;
UPDATE `areatrigger_teleport` SET `id` = 228,`name` = '哀嚎洞穴(副本)-贫瘠之地' WHERE `areatrigger_teleport`.`id` = 228;
UPDATE `areatrigger_teleport` SET `id` = 242,`name` = '剃刀沼泽门口-贫瘠之地' WHERE `areatrigger_teleport`.`id` = 242;
UPDATE `areatrigger_teleport` SET `id` = 244,`name` = '剃刀沼泽(副本)-贫瘠之地' WHERE `areatrigger_teleport`.`id` = 244;
UPDATE `areatrigger_teleport` SET `id` = 257,`name` = '黑暗深渊(副本)-灰谷' WHERE `areatrigger_teleport`.`id` = 257;
UPDATE `areatrigger_teleport` SET `id` = 259,`name` = '黑暗深渊门口-灰谷' WHERE `areatrigger_teleport`.`id` = 259;
UPDATE `areatrigger_teleport` SET `id` = 286,`name` = '奥达曼(副本)A-荒芜之地' WHERE `areatrigger_teleport`.`id` = 286;
UPDATE `areatrigger_teleport` SET `id` = 288,`name` = '奥达曼门口' WHERE `areatrigger_teleport`.`id` = 288;
UPDATE `areatrigger_teleport` SET `id` = 322,`name` = '诺莫瑞根门口A-丹莫罗' WHERE `areatrigger_teleport`.`id` = 322;
UPDATE `areatrigger_teleport` SET `id` = 324,`name` = '诺莫瑞根(副本)A-丹莫罗' WHERE `areatrigger_teleport`.`id` = 324;
UPDATE `areatrigger_teleport` SET `id` = 442,`name` = '剃刀高地(副本)-贫瘠之地' WHERE `areatrigger_teleport`.`id` = 442;
UPDATE `areatrigger_teleport` SET `id` = 444,`name` = '剃刀高地门口-贫瘠之地' WHERE `areatrigger_teleport`.`id` = 444;
UPDATE `areatrigger_teleport` SET `id` = 446,`name` = '阿塔哈卡神庙(副本)-悲伤沼泽' WHERE `areatrigger_teleport`.`id` = 446;
UPDATE `areatrigger_teleport` SET `id` = 448,`name` = '阿塔哈卡神庙门口-悲伤沼泽' WHERE `areatrigger_teleport`.`id` = 448;
UPDATE `areatrigger_teleport` SET `id` = 503,`name` = '暴风城监狱-门口' WHERE `areatrigger_teleport`.`id` = 503;
UPDATE `areatrigger_teleport` SET `id` = 523,`name` = '诺莫瑞根(副本)B-丹莫罗' WHERE `areatrigger_teleport`.`id` = 523;
UPDATE `areatrigger_teleport` SET `id` = 525,`name` = '诺莫瑞根门口B-丹莫罗' WHERE `areatrigger_teleport`.`id` = 525;
UPDATE `areatrigger_teleport` SET `id` = 527,`name` = '泰达希尔-鲁瑟兰村' WHERE `areatrigger_teleport`.`id` = 527;
UPDATE `areatrigger_teleport` SET `id` = 542,`name` = '泰达希尔-达纳苏斯' WHERE `areatrigger_teleport`.`id` = 542;
UPDATE `areatrigger_teleport` SET `id` = 602,`name` = '血色修道院西(墓地)门口' WHERE `areatrigger_teleport`.`id` = 602;
UPDATE `areatrigger_teleport` SET `id` = 604,`name` = '血色修道院西(大教堂)门口' WHERE `areatrigger_teleport`.`id` = 604;
UPDATE `areatrigger_teleport` SET `id` = 606,`name` = '血色修道院东(军械库)门口' WHERE `areatrigger_teleport`.`id` = 606;
UPDATE `areatrigger_teleport` SET `id` = 608,`name` = '血色修道院东(图书馆)门口' WHERE `areatrigger_teleport`.`id` = 608;
UPDATE `areatrigger_teleport` SET `id` = 610,`name` = '血色修道院西(大教堂)副本起点' WHERE `areatrigger_teleport`.`id` = 610;
UPDATE `areatrigger_teleport` SET `id` = 612,`name` = '血色修道院东(军械库)副本起点' WHERE `areatrigger_teleport`.`id` = 612;
UPDATE `areatrigger_teleport` SET `id` = 614,`name` = '血色修道院东(图书馆)副本起点' WHERE `areatrigger_teleport`.`id` = 614;
UPDATE `areatrigger_teleport` SET `id` = 702,`name` = '暴风城-巫师圣殿' WHERE `areatrigger_teleport`.`id` = 702;
UPDATE `areatrigger_teleport` SET `id` = 704,`name` = '暴风城-巫师圣殿入口' WHERE `areatrigger_teleport`.`id` = 704;
UPDATE `areatrigger_teleport` SET `id` = 882,`name` = '奥达曼门口B-荒芜之地' WHERE `areatrigger_teleport`.`id` = 882;
UPDATE `areatrigger_teleport` SET `id` = 902,`name` = '奥达曼(副本)B-荒芜之地' WHERE `areatrigger_teleport`.`id` = 902;
UPDATE `areatrigger_teleport` SET `id` = 922,`name` = '祖尔法拉克门口-塔纳利斯' WHERE `areatrigger_teleport`.`id` = 922;
UPDATE `areatrigger_teleport` SET `id` = 924,`name` = '祖尔法拉克(副本)-塔纳利斯' WHERE `areatrigger_teleport`.`id` = 924;
UPDATE `areatrigger_teleport` SET `id` = 1064,`name` = '奥妮克希亚的巢穴门口-尘泥沼泽' WHERE `areatrigger_teleport`.`id` = 1064;
UPDATE `areatrigger_teleport` SET `id` = 1466,`name` = '黑石深渊(副本)-黑石山' WHERE `areatrigger_teleport`.`id` = 1466;
UPDATE `areatrigger_teleport` SET `id` = 1468,`name` = '黑石塔-灼热峡谷黑手大厅' WHERE `areatrigger_teleport`.`id` = 1468;
UPDATE `areatrigger_teleport` SET `id` = 1470,`name` = '黑石塔-灼热峡谷熔岩之桥' WHERE `areatrigger_teleport`.`id` = 1470;
UPDATE `areatrigger_teleport` SET `id` = 1472,`name` = '黑石深渊门口-黑石山' WHERE `areatrigger_teleport`.`id` = 1472;
UPDATE `areatrigger_teleport` SET `id` = 2166,`name` = '矿道地铁-铁炉堡' WHERE `areatrigger_teleport`.`id` = 2166;
UPDATE `areatrigger_teleport` SET `id` = 2171,`name` = '矿道地铁-暴风城' WHERE `areatrigger_teleport`.`id` = 2171;
UPDATE `areatrigger_teleport` SET `id` = 2173,`name` = '矿道地铁-暴风城' WHERE `areatrigger_teleport`.`id` = 2173;
UPDATE `areatrigger_teleport` SET `id` = 2175,`name` = '矿道地铁-铁炉堡' WHERE `areatrigger_teleport`.`id` = 2175;
UPDATE `areatrigger_teleport` SET `id` = 2214,`name` = '斯坦索姆(副本)B-东瘟疫之地' WHERE `areatrigger_teleport`.`id` = 2214;
UPDATE `areatrigger_teleport` SET `id` = 2216,`name` = '斯坦索姆-东瘟疫之地出口A2' WHERE `areatrigger_teleport`.`id` = 2216;
UPDATE `areatrigger_teleport` SET `id` = 2217,`name` = '斯坦索姆-东瘟疫之地出口A1' WHERE `areatrigger_teleport`.`id` = 2217;
UPDATE `areatrigger_teleport` SET `id` = 2221,`name` = '斯坦索姆门口B-东瘟疫之地' WHERE `areatrigger_teleport`.`id` = 2221;
UPDATE `areatrigger_teleport` SET `id` = 2226,`name` = '怒焰裂谷门口-奥格瑞玛' WHERE `areatrigger_teleport`.`id` = 2226;
UPDATE `areatrigger_teleport` SET `id` = 2230,`name` = '怒焰裂谷(副本)-奥格瑞玛' WHERE `areatrigger_teleport`.`id` = 2230;
UPDATE `areatrigger_teleport` SET `id` = 4743,`name` = '俄特加德要塞- 出口' WHERE `areatrigger_teleport`.`id` = 4743;
UPDATE `areatrigger_teleport` SET `id` = 2530,`name` = '奥格瑞玛-(勇者大厅)入口' WHERE `areatrigger_teleport`.`id` = 2530;
UPDATE `areatrigger_teleport` SET `id` = 2534,`name` = '暴风城-(勇士大厅)入口' WHERE `areatrigger_teleport`.`id` = 2534;
UPDATE `areatrigger_teleport` SET `id` = 2567,`name` = '通灵学院(副本)-西瘟疫之地' WHERE `areatrigger_teleport`.`id` = 2567;
UPDATE `areatrigger_teleport` SET `id` = 2568,`name` = '通灵学院门口-西瘟疫之地' WHERE `areatrigger_teleport`.`id` = 2568;
UPDATE `areatrigger_teleport` SET `id` = 2606,`name` = 'PVP1奥托兰克山谷-部落入口' WHERE `areatrigger_teleport`.`id` = 2606;
UPDATE `areatrigger_teleport` SET `id` = 2608,`name` = 'PVP1奥托兰克山谷-联盟入口' WHERE `areatrigger_teleport`.`id` = 2608;
UPDATE `areatrigger_teleport` SET `id` = 2848,`name` = '奥妮克希亚的巢穴(副本)-尘泥沼泽' WHERE `areatrigger_teleport`.`id` = 2848;
UPDATE `areatrigger_teleport` SET `id` = 2886,`name` = '熔火之桥' WHERE `areatrigger_teleport`.`id` = 2886;
UPDATE `areatrigger_teleport` SET `id` = 2890,`name` = '熔火之心 - 入口, 里面' WHERE `areatrigger_teleport`.`id` = 2890;
UPDATE `areatrigger_teleport` SET `id` = 3126,`name` = '迈拉顿门口B-凄凉之地' WHERE `areatrigger_teleport`.`id` = 3126;
UPDATE `areatrigger_teleport` SET `id` = 3131,`name` = '迈拉顿门口A-凄凉之地' WHERE `areatrigger_teleport`.`id` = 3131;
UPDATE `areatrigger_teleport` SET `id` = 3133,`name` = '迈拉顿(副本)A-凄凉之地' WHERE `areatrigger_teleport`.`id` = 3133;
UPDATE `areatrigger_teleport` SET `id` = 3134,`name` = '迈拉顿(副本)B-凄凉之地' WHERE `areatrigger_teleport`.`id` = 3134;
UPDATE `areatrigger_teleport` SET `id` = 3183,`name` = '厄运之槌东A(副本)-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3183;
UPDATE `areatrigger_teleport` SET `id` = 3184,`name` = '厄运之槌东B(副本)-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3184;
UPDATE `areatrigger_teleport` SET `id` = 3185,`name` = '厄运之槌东C(副本)-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3185;
UPDATE `areatrigger_teleport` SET `id` = 3186,`name` = '厄运之槌西B(副本)-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3186;
UPDATE `areatrigger_teleport` SET `id` = 3187,`name` = '厄运之槌西A(副本)-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3187;
UPDATE `areatrigger_teleport` SET `id` = 3189,`name` = '厄运之槌北(副本)-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3189;
UPDATE `areatrigger_teleport` SET `id` = 3190,`name` = '厄运之槌西B门口-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3190;
UPDATE `areatrigger_teleport` SET `id` = 3191,`name` = '厄运之槌西A门口-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3191;
UPDATE `areatrigger_teleport` SET `id` = 3193,`name` = '厄运之槌北门口-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3193;
UPDATE `areatrigger_teleport` SET `id` = 3194,`name` = '厄运之槌东A门口-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3194;
UPDATE `areatrigger_teleport` SET `id` = 3195,`name` = '厄运之槌东B门口-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3195;
UPDATE `areatrigger_teleport` SET `id` = 3196,`name` = '厄运之槌东C门口-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3196;
UPDATE `areatrigger_teleport` SET `id` = 3197,`name` = '厄运之槌东D门口-菲拉斯' WHERE `areatrigger_teleport`.`id` = 3197;
UPDATE `areatrigger_teleport` SET `id` = 3529,`name` = '熔火之心之窗 (熔岩) 入口' WHERE `areatrigger_teleport`.`id` = 3529;
UPDATE `areatrigger_teleport` SET `id` = 3726,`name` = '黑翼之巢入口-灼热峡谷-燃烧平原-东部王国' WHERE `areatrigger_teleport`.`id` = 3726;
UPDATE `areatrigger_teleport` SET `id` = 3728,`name` = '黑翼之巢出口-黑石山-东部王国' WHERE `areatrigger_teleport`.`id` = 3728;
UPDATE `areatrigger_teleport` SET `id` = 3928,`name` = '祖尔格拉布(副本)-荆棘谷' WHERE `areatrigger_teleport`.`id` = 3928;
UPDATE `areatrigger_teleport` SET `id` = 3930,`name` = '祖尔格拉布门口-荆棘谷' WHERE `areatrigger_teleport`.`id` = 3930;
UPDATE `areatrigger_teleport` SET `id` = 3948,`name` = 'PVP4阿拉希盆地联盟出口' WHERE `areatrigger_teleport`.`id` = 3948;
UPDATE `areatrigger_teleport` SET `id` = 3949,`name` = 'PVP4落锤镇部落入口' WHERE `areatrigger_teleport`.`id` = 3949;
UPDATE `areatrigger_teleport` SET `id` = 3528,`name` = '熔火之心之窗 入口' WHERE `areatrigger_teleport`.`id` = 3528;
UPDATE `areatrigger_teleport` SET `id` = 4006,`name` = '安其拉废墟门口-希利苏斯' WHERE `areatrigger_teleport`.`id` = 4006;
UPDATE `areatrigger_teleport` SET `id` = 4008,`name` = '安其拉废墟(副本)-希利苏斯' WHERE `areatrigger_teleport`.`id` = 4008;
UPDATE `areatrigger_teleport` SET `id` = 4010,`name` = '安其拉神殿(副本)-希利苏斯' WHERE `areatrigger_teleport`.`id` = 4010;
UPDATE `areatrigger_teleport` SET `id` = 4012,`name` = '安其拉神殿门口-希利苏斯' WHERE `areatrigger_teleport`.`id` = 4012;
UPDATE `areatrigger_teleport` SET `id` = 4745,`name` = '俄特加德要塞- 入口' WHERE `areatrigger_teleport`.`id` = 4745;
UPDATE `areatrigger_teleport` SET `id` = 4131,`name` = '卡拉赞门楼(入口处)' WHERE `areatrigger_teleport`.`id` = 4131;
UPDATE `areatrigger_teleport` SET `id` = 4145,`name` = '碎裂大厅出口' WHERE `areatrigger_teleport`.`id` = 4145;
UPDATE `areatrigger_teleport` SET `id` = 4147,`name` = '蒸汽洞窟出口' WHERE `areatrigger_teleport`.`id` = 4147;
UPDATE `areatrigger_teleport` SET `id` = 4149,`name` = '玛瑟里顿的巢穴出口' WHERE `areatrigger_teleport`.`id` = 4149;
UPDATE `areatrigger_teleport` SET `id` = 4150,`name` = '地狱火壁垒' WHERE `areatrigger_teleport`.`id` = 4150;
UPDATE `areatrigger_teleport` SET `id` = 4151,`name` = '破碎大厅' WHERE `areatrigger_teleport`.`id` = 4151;
UPDATE `areatrigger_teleport` SET `id` = 4152,`name` = '蒸汽洞窟' WHERE `areatrigger_teleport`.`id` = 4152;
UPDATE `areatrigger_teleport` SET `id` = 4153,`name` = '玛瑟里顿的巢穴' WHERE `areatrigger_teleport`.`id` = 4153;
UPDATE `areatrigger_teleport` SET `id` = 4297,`name` = '地狱火壁垒出口' WHERE `areatrigger_teleport`.`id` = 4297;
UPDATE `areatrigger_teleport` SET `id` = 4311,`name` = '到海家尔人类营地之门' WHERE `areatrigger_teleport`.`id` = 4311;
UPDATE `areatrigger_teleport` SET `id` = 4312,`name` = '从海家尔到部落营地之门' WHERE `areatrigger_teleport`.`id` = 4312;
UPDATE `areatrigger_teleport` SET `id` = 4313,`name` = '从海家尔到暗夜向导村庄生命之树之门' WHERE `areatrigger_teleport`.`id` = 4313;
UPDATE `areatrigger_teleport` SET `id` = 4319,`name` = '海家尔山峰入口' WHERE `areatrigger_teleport`.`id` = 4319;
UPDATE `areatrigger_teleport` SET `id` = 4320,`name` = '黑色沼泽出口' WHERE `areatrigger_teleport`.`id` = 4320;
UPDATE `areatrigger_teleport` SET `id` = 4321,`name` = '时光之穴出口' WHERE `areatrigger_teleport`.`id` = 4321;
UPDATE `areatrigger_teleport` SET `id` = 4322,`name` = '黑色沼泽出口' WHERE `areatrigger_teleport`.`id` = 4322;
UPDATE `areatrigger_teleport` SET `id` = 4323,`name` = '从海家尔到CoT 主门' WHERE `areatrigger_teleport`.`id` = 4323;
UPDATE `areatrigger_teleport` SET `id` = 4324,`name` = '时光之穴入口' WHERE `areatrigger_teleport`.`id` = 4324;
UPDATE `areatrigger_teleport` SET `id` = 4352,`name` = '外域到黑暗之门' WHERE `areatrigger_teleport`.`id` = 4352;
UPDATE `areatrigger_teleport` SET `id` = 4354,`name` = '黑暗之门到外域' WHERE `areatrigger_teleport`.`id` = 4354;
UPDATE `areatrigger_teleport` SET `id` = 4363,`name` = '沼泽洞穴入口' WHERE `areatrigger_teleport`.`id` = 4363;
UPDATE `areatrigger_teleport` SET `id` = 4364,`name` = '蒸汽洞窟入口' WHERE `areatrigger_teleport`.`id` = 4364;
UPDATE `areatrigger_teleport` SET `id` = 4365,`name` = '奴隶围栏入口' WHERE `areatrigger_teleport`.`id` = 4365;
UPDATE `areatrigger_teleport` SET `id` = 4366,`name` = '蒸汽洞窟出口' WHERE `areatrigger_teleport`.`id` = 4366;
UPDATE `areatrigger_teleport` SET `id` = 4367,`name` = '沼泽洞穴出口' WHERE `areatrigger_teleport`.`id` = 4367;
UPDATE `areatrigger_teleport` SET `id` = 4379,`name` = '奴隶围栏出口' WHERE `areatrigger_teleport`.`id` = 4379;
UPDATE `areatrigger_teleport` SET `id` = 4386,`name` = '逐日岛到东瘟疫之地' WHERE `areatrigger_teleport`.`id` = 4386;
UPDATE `areatrigger_teleport` SET `id` = 4397,`name` = '暗影迷宫出口' WHERE `areatrigger_teleport`.`id` = 4397;
UPDATE `areatrigger_teleport` SET `id` = 4399,`name` = '塞泰克大厅出口' WHERE `areatrigger_teleport`.`id` = 4399;
UPDATE `areatrigger_teleport` SET `id` = 4401,`name` = '法力坟墓出口' WHERE `areatrigger_teleport`.`id` = 4401;
UPDATE `areatrigger_teleport` SET `id` = 4403,`name` = '奥金顿墓穴出口' WHERE `areatrigger_teleport`.`id` = 4403;
UPDATE `areatrigger_teleport` SET `id` = 4404,`name` = '奥金顿墓穴入口' WHERE `areatrigger_teleport`.`id` = 4404;
UPDATE `areatrigger_teleport` SET `id` = 4405,`name` = '法力坟墓入口' WHERE `areatrigger_teleport`.`id` = 4405;
UPDATE `areatrigger_teleport` SET `id` = 4406,`name` = '塞泰克大厅入口' WHERE `areatrigger_teleport`.`id` = 4406;
UPDATE `areatrigger_teleport` SET `id` = 4407,`name` = '暗影迷宫入口' WHERE `areatrigger_teleport`.`id` = 4407;
UPDATE `areatrigger_teleport` SET `id` = 4409,`name` = '东瘟疫之地到逐日岛' WHERE `areatrigger_teleport`.`id` = 4409;
UPDATE `areatrigger_teleport` SET `id` = 4416,`name` = '盘牙洞穴入口' WHERE `areatrigger_teleport`.`id` = 4416;
UPDATE `areatrigger_teleport` SET `id` = 4436,`name` = '卡拉赞门房 (出口)' WHERE `areatrigger_teleport`.`id` = 4436;
UPDATE `areatrigger_teleport` SET `id` = 4455,`name` = '拱廊区出口' WHERE `areatrigger_teleport`.`id` = 4455;
UPDATE `areatrigger_teleport` SET `id` = 4457,`name` = '凤凰大厅出口' WHERE `areatrigger_teleport`.`id` = 4457;
UPDATE `areatrigger_teleport` SET `id` = 4459,`name` = '秘术区出口' WHERE `areatrigger_teleport`.`id` = 4459;
UPDATE `areatrigger_teleport` SET `id` = 4461,`name` = '机械区出口' WHERE `areatrigger_teleport`.`id` = 4461;
UPDATE `areatrigger_teleport` SET `id` = 4467,`name` = '秘术区入口' WHERE `areatrigger_teleport`.`id` = 4467;
UPDATE `areatrigger_teleport` SET `id` = 4468,`name` = '拱廊区入口' WHERE `areatrigger_teleport`.`id` = 4468;
UPDATE `areatrigger_teleport` SET `id` = 4469,`name` = '机械区入口' WHERE `areatrigger_teleport`.`id` = 4469;
UPDATE `areatrigger_teleport` SET `id` = 4470,`name` = '凤凰大厅入口' WHERE `areatrigger_teleport`.`id` = 4470;
UPDATE `areatrigger_teleport` SET `id` = 4487,`name` = '海家尔峰出口' WHERE `areatrigger_teleport`.`id` = 4487;
UPDATE `areatrigger_teleport` SET `id` = 4534,`name` = '格鲁尔巢穴出口' WHERE `areatrigger_teleport`.`id` = 4534;
UPDATE `areatrigger_teleport` SET `id` = 4535,`name` = '格鲁尔巢穴入口' WHERE `areatrigger_teleport`.`id` = 4535;
UPDATE `areatrigger_teleport` SET `id` = 4598,`name` = '黑暗神庙' WHERE `areatrigger_teleport`.`id` = 4598;
UPDATE `areatrigger_teleport` SET `id` = 4619,`name` = '黑暗神庙出口' WHERE `areatrigger_teleport`.`id` = 4619;
UPDATE `areatrigger_teleport` SET `id` = 4418,`name` = '盘牙洞穴出口' WHERE `areatrigger_teleport`.`id` = 4418;
UPDATE `areatrigger_teleport` SET `id` = 4523,`name` = '索克雷萨出口' WHERE `areatrigger_teleport`.`id` = 4523;
UPDATE `areatrigger_teleport` SET `id` = 4738,`name` = '祖阿曼入口' WHERE `areatrigger_teleport`.`id` = 4738;
UPDATE `areatrigger_teleport` SET `id` = 4739,`name` = '祖阿曼出口' WHERE `areatrigger_teleport`.`id` = 4739;
UPDATE `areatrigger_teleport` SET `id` = 943,`name` = '信仰的飞跃 - 秋季结束' WHERE `areatrigger_teleport`.`id` = 943;
UPDATE `areatrigger_teleport` SET `id` = 4561,`name` = '侵略点:灾难 (回归)' WHERE `areatrigger_teleport`.`id` = 4561;
UPDATE `areatrigger_teleport` SET `id` = 4562,`name` = '侵略点:灾难 (回归)' WHERE `areatrigger_teleport`.`id` = 4562;
UPDATE `areatrigger_teleport` SET `id` = 4135,`name` = '卡拉赞上层' WHERE `areatrigger_teleport`.`id` = 4135;
UPDATE `areatrigger_teleport` SET `id` = 4885,`name` = '魔班主任平台出口' WHERE `areatrigger_teleport`.`id` = 4885;
UPDATE `areatrigger_teleport` SET `id` = 4887,`name` = '魔班主任平台入口' WHERE `areatrigger_teleport`.`id` = 4887;
UPDATE `areatrigger_teleport` SET `id` = 4889,`name` = '太阳之井高地入口' WHERE `areatrigger_teleport`.`id` = 4889;
UPDATE `areatrigger_teleport` SET `id` = 4891,`name` = '太阳之井高地出口' WHERE `areatrigger_teleport`.`id` = 4891;
UPDATE `areatrigger_teleport` SET `id` = 4747,`name` = '俄特加德要塞- 出口' WHERE `areatrigger_teleport`.`id` = 4747;
UPDATE `areatrigger_teleport` SET `id` = 4741,`name` = '俄特加德要塞- 出口' WHERE `areatrigger_teleport`.`id` = 4741;
UPDATE `areatrigger_teleport` SET `id` = 4983,`name` = '奈萨斯 70 入口' WHERE `areatrigger_teleport`.`id` = 4983;
UPDATE `areatrigger_teleport` SET `id` = 4981,`name` = '奈萨斯 70 出口' WHERE `areatrigger_teleport`.`id` = 4981;
UPDATE `areatrigger_teleport` SET `id` = 5246,`name` = '永恒之眼 - 入口' WHERE `areatrigger_teleport`.`id` = 5246;
UPDATE `areatrigger_teleport` SET `id` = 5191,`name` = '纳克萨玛斯 - 入口 4' WHERE `areatrigger_teleport`.`id` = 5191;
UPDATE `areatrigger_teleport` SET `id` = 5192,`name` = '纳克萨玛斯 - 入口 2' WHERE `areatrigger_teleport`.`id` = 5192;
UPDATE `areatrigger_teleport` SET `id` = 5193,`name` = '纳克萨玛斯 - 入口 3' WHERE `areatrigger_teleport`.`id` = 5193;
UPDATE `areatrigger_teleport` SET `id` = 5194,`name` = '纳克萨玛斯 - 入口 1' WHERE `areatrigger_teleport`.`id` = 5194;
UPDATE `areatrigger_teleport` SET `id` = 5196,`name` = '纳克萨玛斯 - 出口 4' WHERE `areatrigger_teleport`.`id` = 5196;
UPDATE `areatrigger_teleport` SET `id` = 5197,`name` = '纳克萨玛斯 - 出口 2' WHERE `areatrigger_teleport`.`id` = 5197;
UPDATE `areatrigger_teleport` SET `id` = 5198,`name` = '纳克萨玛斯 - 出口 3' WHERE `areatrigger_teleport`.`id` = 5198;
UPDATE `areatrigger_teleport` SET `id` = 5199,`name` = '纳克萨玛斯 - 出口 1' WHERE `areatrigger_teleport`.`id` = 5199;
UPDATE `areatrigger_teleport` SET `id` = 5150,`name` = '往事引导 入口' WHERE `areatrigger_teleport`.`id` = 5150;
UPDATE `areatrigger_teleport` SET `id` = 5181,`name` = '斯坦索姆的抉择 (出口)' WHERE `areatrigger_teleport`.`id` = 5181;
UPDATE `areatrigger_teleport` SET `id` = 5209,`name` = '紫罗兰堡 - 入口' WHERE `areatrigger_teleport`.`id` = 5209;
UPDATE `areatrigger_teleport` SET `id` = 5211,`name` = '紫罗兰堡 - 出口' WHERE `areatrigger_teleport`.`id` = 5211;
UPDATE `areatrigger_teleport` SET `id` = 5206,`name` = '刚德拉克 - 入口' WHERE `areatrigger_teleport`.`id` = 5206;
UPDATE `areatrigger_teleport` SET `id` = 5205,`name` = '刚德拉克 - 入口' WHERE `areatrigger_teleport`.`id` = 5205;
UPDATE `areatrigger_teleport` SET `id` = 5277,`name` = '刚德拉克 - 出口 04' WHERE `areatrigger_teleport`.`id` = 5277;
UPDATE `areatrigger_teleport` SET `id` = 5231,`name` = '刚德拉克 - 出口 02' WHERE `areatrigger_teleport`.`id` = 5231;
UPDATE `areatrigger_teleport` SET `id` = 5093,`name` = '雷光大厅 - 入口' WHERE `areatrigger_teleport`.`id` = 5093;
UPDATE `areatrigger_teleport` SET `id` = 5091,`name` = '雷光大厅 - 出口' WHERE `areatrigger_teleport`.`id` = 5091;
UPDATE `areatrigger_teleport` SET `id` = 5010,`name` = '奥杜亚, 石之大厅 (入口)' WHERE `areatrigger_teleport`.`id` = 5010;
UPDATE `areatrigger_teleport` SET `id` = 5012,`name` = '石之大厅 - 出口' WHERE `areatrigger_teleport`.`id` = 5012;
UPDATE `areatrigger_teleport` SET `id` = 5117,`name` = '阿兹欧-奈幽 (入口)' WHERE `areatrigger_teleport`.`id` = 5117;
UPDATE `areatrigger_teleport` SET `id` = 5115,`name` = '阿兹欧-奈幽 (出口)' WHERE `areatrigger_teleport`.`id` = 5115;
UPDATE `areatrigger_teleport` SET `id` = 5113,`name` = '阿兹欧-奈幽 - 出口?' WHERE `areatrigger_teleport`.`id` = 5113;
UPDATE `areatrigger_teleport` SET `id` = 5215,`name` = '阿兹欧-奈幽: 安卡罕特:古王国 - 入口' WHERE `areatrigger_teleport`.`id` = 5215;
UPDATE `areatrigger_teleport` SET `id` = 5213,`name` = '古王国 - 出口' WHERE `areatrigger_teleport`.`id` = 5213;
UPDATE `areatrigger_teleport` SET `id` = 5243,`name` = '守护巨龙之间, 黑曜圣所 (入口)' WHERE `areatrigger_teleport`.`id` = 5243;
UPDATE `areatrigger_teleport` SET `id` = 5241,`name` = '守护巨龙之间, 黑曜圣所 (出口)' WHERE `areatrigger_teleport`.`id` = 5241;
UPDATE `areatrigger_teleport` SET `id` = 4998,`name` = '德拉克萨隆 入口' WHERE `areatrigger_teleport`.`id` = 4998;
UPDATE `areatrigger_teleport` SET `id` = 5000,`name` = '德拉克萨隆 出口' WHERE `areatrigger_teleport`.`id` = 5000;
UPDATE `areatrigger_teleport` SET `id` = 5290,`name` = '永恒之眼 (入口)' WHERE `areatrigger_teleport`.`id` = 5290;
UPDATE `areatrigger_teleport` SET `id` = 5001,`name` = '奥核之眼 - 出口' WHERE `areatrigger_teleport`.`id` = 5001;
UPDATE `areatrigger_teleport` SET `id` = 4520,`name` = '卡拉赞, 广场 (出口)' WHERE `areatrigger_teleport`.`id` = 4520;
UPDATE `areatrigger_teleport` SET `id` = 5379,`name` = '奥杜亚团队 入口' WHERE `areatrigger_teleport`.`id` = 5379;
UPDATE `areatrigger_teleport` SET `id` = 5381,`name` = '奥杜亚团队 出口' WHERE `areatrigger_teleport`.`id` = 5381;
UPDATE `areatrigger_teleport` SET `id` = 5262,`name` = '亚夏梵穹殿 (出口)' WHERE `areatrigger_teleport`.`id` = 5262;
UPDATE `areatrigger_teleport` SET `id` = 5258,`name` = '亚夏梵穹殿 (入口)' WHERE `areatrigger_teleport`.`id` = 5258;
UPDATE `areatrigger_teleport` SET `id` = 5273,`name` = '达拉然水井' WHERE `areatrigger_teleport`.`id` = 5273;
UPDATE `areatrigger_teleport` SET `id` = 5508,`name` = '十字军试炼 (出口)' WHERE `areatrigger_teleport`.`id` = 5508;
UPDATE `areatrigger_teleport` SET `id` = 5503,`name` = '十字军试炼 (入口)' WHERE `areatrigger_teleport`.`id` = 5503;
UPDATE `areatrigger_teleport` SET `id` = 5505,`name` = '勇士试炼 (入口)' WHERE `areatrigger_teleport`.`id` = 5505;
UPDATE `areatrigger_teleport` SET `id` = 5510,`name` = '勇士试炼 (出口)' WHERE `areatrigger_teleport`.`id` = 5510;
UPDATE `areatrigger_teleport` SET `id` = 5670,`name` = '寒冰皇冠城塞 (入口)' WHERE `areatrigger_teleport`.`id` = 5670;
UPDATE `areatrigger_teleport` SET `id` = 5668,`name` = '寒冰皇冠城塞 (出口)' WHERE `areatrigger_teleport`.`id` = 5668;
UPDATE `areatrigger_teleport` SET `id` = 5635,`name` = '众魂熔炉 (入口)' WHERE `areatrigger_teleport`.`id` = 5635;
UPDATE `areatrigger_teleport` SET `id` = 5636,`name` = '倒影大厅 (入口)' WHERE `areatrigger_teleport`.`id` = 5636;
UPDATE `areatrigger_teleport` SET `id` = 5637,`name` = '萨伦之渊 (入口)' WHERE `areatrigger_teleport`.`id` = 5637;
UPDATE `areatrigger_teleport` SET `id` = 5642,`name` = '众魂熔炉 (出口)' WHERE `areatrigger_teleport`.`id` = 5642;
UPDATE `areatrigger_teleport` SET `id` = 5643,`name` = '萨伦之渊 (出口)' WHERE `areatrigger_teleport`.`id` = 5643;
UPDATE `areatrigger_teleport` SET `id` = 5646,`name` = '倒影大厅 (出口)' WHERE `areatrigger_teleport`.`id` = 5646;
UPDATE `areatrigger_teleport` SET `id` = 5683,`name` = '萨伦之渊 (出口) 倒影大厅 (入口)' WHERE `areatrigger_teleport`.`id` = 5683;
UPDATE `areatrigger_teleport` SET `id` = 5688,`name` = '众魂熔炉 (出口) 萨伦之渊 (入口)' WHERE `areatrigger_teleport`.`id` = 5688;
UPDATE `areatrigger_teleport` SET `id` = 5051,`name` = 'q12710:1楼' WHERE `areatrigger_teleport`.`id` = 5051;
UPDATE `areatrigger_teleport` SET `id` = 5079,`name` = 'q12710: 2楼' WHERE `areatrigger_teleport`.`id` = 5079;
UPDATE `areatrigger_teleport` SET `id` = 5869,`name` = '晶红圣殿 (入口)' WHERE `areatrigger_teleport`.`id` = 5869;
UPDATE `areatrigger_teleport` SET `id` = 5872,`name` = '晶红圣殿 (出口)' WHERE `areatrigger_teleport`.`id` = 5872;
UPDATE `areatrigger_teleport` SET `id` = 5276,`name` = '刚德拉克 - 出口 03' WHERE `areatrigger_teleport`.`id` = 5276;
UPDATE `areatrigger_teleport` SET `id` = 5233,`name` = '刚德拉克 - 出口 01' WHERE `areatrigger_teleport`.`id` = 5233;
UPDATE `areatrigger_teleport` SET `id` = 4612,`name` = '生态船 - 麦克纳尔' WHERE `areatrigger_teleport`.`id` = 4612;
UPDATE `areatrigger_teleport` SET `id` = 4614,`name` = '能源舰- 生态船' WHERE `areatrigger_teleport`.`id` = 4614;
UPDATE `areatrigger_teleport` SET `id` = 2406,`name` = '影牙城堡 - 南落目标' WHERE `areatrigger_teleport`.`id` = 2406;
UPDATE `areatrigger_teleport` SET `id` = 2407,`name` = '影牙城堡 - 南落目标' WHERE `areatrigger_teleport`.`id` = 2407;
UPDATE `areatrigger_teleport` SET `id` = 2408,`name` = '影牙城堡 Front Fall Exit Target' WHERE `areatrigger_teleport`.`id` = 2408;
UPDATE `areatrigger_teleport` SET `id` = 2409,`name` = '影牙城堡 Front Fall Exit Target' WHERE `areatrigger_teleport`.`id` = 2409;
UPDATE `areatrigger_teleport` SET `id` = 2410,`name` = '影牙城堡 - North Fall Target' WHERE `areatrigger_teleport`.`id` = 2410;
UPDATE `areatrigger_teleport` SET `id` = 2411,`name` = '影牙城堡 - North Fall Target' WHERE `areatrigger_teleport`.`id` = 2411;
UPDATE `areatrigger_teleport` SET `id` = 4233,`name` = '永歌森林 - Duskwither UP Target' WHERE `areatrigger_teleport`.`id` = 4233;
UPDATE `areatrigger_teleport` SET `id` = 4267,`name` = '永歌森林 - Duskwither DOWN Target' WHERE `areatrigger_teleport`.`id` = 4267;
UPDATE `areatrigger_teleport` SET `id` = 4304,`name` = '地狱火城墙 - Omor Exit Target' WHERE `areatrigger_teleport`.`id` = 4304;
UPDATE `areatrigger_teleport` SET `id` = 5148,`name` = 'CoT Stratholme - Exit Target' WHERE `areatrigger_teleport`.`id` = 5148;
UPDATE `areatrigger_teleport` SET `id` = 4917,`name` = '竞技场 - 纳格兰 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4917;
UPDATE `areatrigger_teleport` SET `id` = 4919,`name` = '竞技场 - 刀锋山 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4919;
UPDATE `areatrigger_teleport` SET `id` = 4921,`name` = '竞技场 - 刀锋山 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4921;
UPDATE `areatrigger_teleport` SET `id` = 4922,`name` = '竞技场 - 刀锋山 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4922;
UPDATE `areatrigger_teleport` SET `id` = 4923,`name` = '竞技场 - 刀锋山 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4923;
UPDATE `areatrigger_teleport` SET `id` = 4924,`name` = '竞技场 - 刀锋山 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4924;
UPDATE `areatrigger_teleport` SET `id` = 4925,`name` = '竞技场 - 刀锋山 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4925;
UPDATE `areatrigger_teleport` SET `id` = 4927,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4927;
UPDATE `areatrigger_teleport` SET `id` = 4928,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4928;
UPDATE `areatrigger_teleport` SET `id` = 4929,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4929;
UPDATE `areatrigger_teleport` SET `id` = 4930,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4930;
UPDATE `areatrigger_teleport` SET `id` = 4931,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4931;
UPDATE `areatrigger_teleport` SET `id` = 4932,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4932;
UPDATE `areatrigger_teleport` SET `id` = 4933,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4933;
UPDATE `areatrigger_teleport` SET `id` = 4934,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4934;
UPDATE `areatrigger_teleport` SET `id` = 4935,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4935;
UPDATE `areatrigger_teleport` SET `id` = 4936,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4936;
UPDATE `areatrigger_teleport` SET `id` = 4941,`name` = '竞技场 - 幽暗城 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4941;
UPDATE `areatrigger_teleport` SET `id` = 4944,`name` = '竞技场 - 刀锋山 - Teleport Target - Game On' WHERE `areatrigger_teleport`.`id` = 4944;
UPDATE `areatrigger_teleport` SET `id` = 5326,`name` = '竞技场 - 达拉然竞技场 - Teleport Target' WHERE `areatrigger_teleport`.`id` = 5326;
UPDATE `areatrigger_teleport` SET `id` = 5328,`name` = '竞技场 - 达拉然竞技场 - Teleport Target' WHERE `areatrigger_teleport`.`id` = 5328;
UPDATE `areatrigger_teleport` SET `id` = 5329,`name` = '竞技场 - 达拉然竞技场 - Teleport Target' WHERE `areatrigger_teleport`.`id` = 5329;
UPDATE `areatrigger_teleport` SET `id` = 5330,`name` = '竞技场 - 达拉然竞技场 - Teleport Target' WHERE `areatrigger_teleport`.`id` = 5330;
UPDATE `areatrigger_teleport` SET `id` = 5331,`name` = '竞技场 - 达拉然竞技场 - Teleport Target' WHERE `areatrigger_teleport`.`id` = 5331;
UPDATE `areatrigger_teleport` SET `id` = 5447,`name` = '竞技场 - 奥格瑞玛 - Teleport Target 3' WHERE `areatrigger_teleport`.`id` = 5447;
UPDATE `areatrigger_teleport` SET `id` = 5127,`name` = '黑锋要塞 (E.K.) Top Return Target' WHERE `areatrigger_teleport`.`id` = 5127;
UPDATE `areatrigger_teleport` SET `id` = 5128,`name` = '黑锋要塞 (E.K.) Top 西部 Target' WHERE `areatrigger_teleport`.`id` = 5128;
UPDATE `areatrigger_teleport` SET `id` = 5129,`name` = '黑锋要塞 (E.K.) Top Return Target' WHERE `areatrigger_teleport`.`id` = 5129;
UPDATE `areatrigger_teleport` SET `id` = 5130,`name` = '黑锋要塞 (E.K.) Top 南部 Target' WHERE `areatrigger_teleport`.`id` = 5130;
UPDATE `areatrigger_teleport` SET `id` = 5131,`name` = '黑锋要塞 (E.K.) Top Return Target' WHERE `areatrigger_teleport`.`id` = 5131;
UPDATE `areatrigger_teleport` SET `id` = 5132,`name` = '黑锋要塞 (E.K.) Top 北部 Target' WHERE `areatrigger_teleport`.`id` = 5132;
UPDATE `areatrigger_teleport` SET `id` = 5133,`name` = '黑锋要塞 (E.K.) Top Return Target' WHERE `areatrigger_teleport`.`id` = 5133;
UPDATE `areatrigger_teleport` SET `id` = 5134,`name` = '黑锋要塞 (E.K.) Top 东部 Target' WHERE `areatrigger_teleport`.`id` = 5134;
UPDATE `areatrigger_teleport` SET `id` = 5135,`name` = '黑锋要塞 (E.K.) 中间 -> 底部 Target' WHERE `areatrigger_teleport`.`id` = 5135;
UPDATE `areatrigger_teleport` SET `id` = 5136,`name` = '黑锋要塞 (E.K.) 中间 -> 底部 Target' WHERE `areatrigger_teleport`.`id` = 5136;
UPDATE `areatrigger_teleport` SET `id` = 5137,`name` = '黑锋要塞 (E.K.) 底部 -> 中间 Target' WHERE `areatrigger_teleport`.`id` = 5137;
UPDATE `areatrigger_teleport` SET `id` = 5138,`name` = '黑锋要塞 (E.K.) 底部 -> 地面 Target' WHERE `areatrigger_teleport`.`id` = 5138;
UPDATE `areatrigger_teleport` SET `id` = 2547,`name` = '通灵学院- Exit Porch Target 001' WHERE `areatrigger_teleport`.`id` = 2547;
UPDATE `areatrigger_teleport` SET `id` = 2548,`name` = '通灵学院 - Exit Porch Target 001' WHERE `areatrigger_teleport`.`id` = 2548;
UPDATE `areatrigger_teleport` SET `id` = 2549,`name` = '通灵学院 - Exit Porch Target 001' WHERE `areatrigger_teleport`.`id` = 2549;